language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: '3.7'
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

install:
  - pip install requests
  - pip install coverage
  - pip install codecov

script:
  - coverage run -m unittest

after_success:
  - codecov
